// 10 sample results from https://api.artic.edu/api/v1/artworks
[
	{
		id: 70430,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/70430',
		is_boosted: false,
		title: "Child's Tunic",
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBQAFAPQAAFk6Hlo6IVg6I2hDJGFAKG9NLW9OMm5SOm9UPGxWRGtYSm5cTHtoV4RyYIVxY4R3bo5+bpB9bpmGdpqNgpuPhqOZjqSbkK2mnq+poQAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAFAAUAAAUVIJQ8DmUdwRBhCFFUDhAY0rUozBQCADs=',
			width: 7448,
			height: 8245,
			alt_text: 'A work made of linen and wool, tapestry weave.',
		},
		main_reference_number: '1914.713',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: -30,
		date_end: 700,
		date_display:
			'Roman period (30 BCE–641 CE)-Arab period (641–969), 7th century',
		date_qualifier_title: 'Made',
		date_qualifier_id: 4,
		artist_display: 'Coptic\nEgypt',
		place_of_origin: 'Egypt',
		description: null,
		short_description: null,
		dimensions: '48.3 × 47 cm (19 × 18 1/2 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 47,
				height: 48,
				diameter: null,
				clarification: null,
			},
		],
		medium_display: 'Linen and wool, tapestry weave',
		inscriptions: null,
		credit_line: 'Gift of Martin A. Ryerson to the Antiquarian Society',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: null,
		publishing_verification_level: 'Web Basic',
		internal_department_id: 4,
		fiscal_year: null,
		fiscal_year_deaccession: null,
		is_public_domain: true,
		is_zoomable: true,
		max_zoom_window_size: -1,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 40,
			l: 68,
			s: 6,
			percentage: 0.0004527609433385922,
			population: 223,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Costume and Accessories',
		artwork_type_id: 12,
		department_title: 'Textiles',
		department_id: 'PC-14',
		artist_id: 29840,
		artist_title: 'Coptic',
		alt_artist_ids: [],
		artist_ids: [29840],
		artist_titles: ['Coptic'],
		category_ids: ['PC-14'],
		category_titles: ['Textiles'],
		term_titles: [
			'roman period (egyptian)',
			'textile',
			'weaving',
			'costume',
			'dress (garment)',
			'clothing',
		],
		style_id: 'TM-4315',
		style_title: 'roman period (egyptian)',
		alt_style_ids: [],
		style_ids: ['TM-4315'],
		style_titles: ['roman period (egyptian)'],
		classification_id: 'TM-69',
		classification_title: 'textile',
		alt_classification_ids: ['TM-159', 'TM-81', 'TM-11897', 'TM-12173'],
		classification_ids: ['TM-69', 'TM-159', 'TM-81', 'TM-11897', 'TM-12173'],
		classification_titles: [
			'textile',
			'weaving',
			'costume',
			'dress (garment)',
			'clothing',
		],
		subject_id: null,
		alt_subject_ids: [],
		subject_ids: [],
		subject_titles: [],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: [],
		image_id: '96de38c9-b49e-c8ce-bf15-6828fb95738f',
		alt_image_ids: ['771d1750-25a5-258c-8903-8905157f9c9e'],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['1914.713'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ["Child's Tunic"],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T17:25:26-05:00',
		updated_at: '2025-04-10T17:30:25-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 36076,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/36076',
		is_boosted: false,
		title: 'Mourning Sampler',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBwAFAPUAAJR/XpeDY5GBa5mIaJyMcaCObqaTeqaXfKuYfKmcg6mchqqehrShgrakhrimh7yqib2rj7+uj7Kok7Ook7SrlLmqkbusk7yvl7evnbium8Kvkse1ksOwlcW0lsWzmcm4mczAqtPBptjKsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAHAAUAAAYhwNBn03lEPCKIQ9NgcECYjGEysSQoF8FicagUBoQAABEEADs=',
			width: 8703,
			height: 6273,
			alt_text:
				'A work made of silk, warp-float faced 4:1 satin weave; embroidered with silk and silk chenille in split, surface satin, and stem stitches; couching.',
		},
		main_reference_number: '1971.146',
		has_not_been_viewed_much: false,
		boost_rank: null,
		date_start: 1800,
		date_end: 1820,
		date_display: 'c. 1810',
		date_qualifier_title: 'Made',
		date_qualifier_id: 4,
		artist_display:
			"Mary Balch's School\nProvidence, Rhode Island, United States",
		place_of_origin: 'Rhode Island',
		description:
			'<p>The inscription on this mourning sampler commemorates the deaths of Nicholas (1767–1797) and Mary Bullock (died 1802). It is likely that was was stitched by either Mary or Louise (Louisa) Winsor, daughters of Mary Bullock Winsor (1767-1816) and Nicholas Winsor (1767-1797). The family connection and style of this piece, and other related works, link it to Mary Balch’s school in Providence. The inclusion of the trumpeting angels indicates that this piece is among the earliest mourning embroideries made at the school. Silk on silk embroidery demonstrated advances needlework skills for a young women. This memorial sampler, along with other types of mourning art, is not a morbid tribute, but rather a beautiful and sophisticated expression of sentiment for the dearly departed.</p>\n',
		short_description: null,
		dimensions: '42.2 × 58.8 cm (16 1/2 × 23 1/8 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 58,
				height: 42,
				diameter: null,
				clarification: null,
			},
		],
		medium_display:
			'Silk, warp-float faced 4:1 satin weave; embroidered with silk and silk chenille in split, surface satin, and stem stitches; couching',
		inscriptions: null,
		credit_line:
			'The Art Institute of Chicago, Department of Textiles Collection',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: null,
		publishing_verification_level: 'Web Basic',
		internal_department_id: 4,
		fiscal_year: null,
		fiscal_year_deaccession: null,
		is_public_domain: true,
		is_zoomable: true,
		max_zoom_window_size: -1,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 39,
			l: 66,
			s: 49,
			percentage: 0.00040480698958431614,
			population: 221,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Textile',
		artwork_type_id: 5,
		department_title: 'Textiles',
		department_id: 'PC-14',
		artist_id: 78609,
		artist_title: "Mary Balch's School",
		alt_artist_ids: [],
		artist_ids: [78609],
		artist_titles: ["Mary Balch's School"],
		category_ids: ['PC-14'],
		category_titles: ['Textiles'],
		term_titles: [
			'Mourning',
			'needleworking',
			'americas',
			'textile',
			'needlework (visual works)',
			'Burial',
			'death',
			'embroidery',
			'embroidering',
			'silk (fiber)',
		],
		style_id: 'TM-6515',
		style_title: 'americas',
		alt_style_ids: [],
		style_ids: ['TM-6515'],
		style_titles: ['americas'],
		classification_id: 'TM-69',
		classification_title: 'textile',
		alt_classification_ids: ['TM-83', 'TM-158'],
		classification_ids: ['TM-69', 'TM-83', 'TM-158'],
		classification_titles: [
			'textile',
			'needlework (visual works)',
			'embroidery',
		],
		subject_id: 'TM-15520',
		alt_subject_ids: ['TM-15521', 'TM-12097'],
		subject_ids: ['TM-15520', 'TM-15521', 'TM-12097'],
		subject_titles: ['Mourning', 'Burial', 'death'],
		material_id: null,
		alt_material_ids: ['TM-3688'],
		material_ids: ['TM-3688'],
		material_titles: ['silk (fiber)'],
		technique_id: 'TM-4235',
		alt_technique_ids: ['TM-3914'],
		technique_ids: ['TM-4235', 'TM-3914'],
		technique_titles: ['needleworking', 'embroidering'],
		theme_titles: [],
		image_id: 'f373c915-0bc9-2034-f094-efdd29520911',
		alt_image_ids: [],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['1971.146'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Mourning Sampler'],
				weight: 503,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:55:02-05:00',
		updated_at: '2025-04-10T16:55:23-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 270001,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/270001',
		is_boosted: false,
		title: 'Panoafricano',
		alt_titles: [],
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhCAAFAPUAAH5nXmhjYG1pZn94dn94d4NqX4VrYIRrYYJsY4RsYoFsZYluZIpuZIVuaYZvaYZxa4lyaYtyaIdzdYl1eJJ9c5N/doiAf5aBd5OCe5eCeJSDe5iCeYeGhJOGgJOJhpyPipiNjZmNjpqPkJqRkZyTlJ6UlZ6UlqKbmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAIAAUAAAYlwA8Fc6loNprOoQFINBARDmESIEgEFs+BoSgwHpFTaCQKkUqlIAA7',
			width: 10396,
			height: 6801,
			alt_text:
				'A work made of printed length of plain-weave cotton; both selvages present.',
		},
		main_reference_number: '2024.210',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 2019,
		date_end: 2019,
		date_display: '2019',
		date_qualifier_title: 'Made',
		date_qualifier_id: 4,
		artist_display:
			'Yonamine (Angolan, born 1975)\nJohn Arthur Liebenberg (South African, 1958-2020)\nwith support from Jahmek Contemporary Art (Angolan, founded 2018)',
		place_of_origin: 'Angola',
		description: null,
		short_description: null,
		dimensions: '548.7 × 114.3 cm (216 × 45 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 114,
				height: 548,
				diameter: null,
				clarification: null,
			},
		],
		medium_display:
			'Printed length of plain-weave cotton; both selvages present',
		inscriptions: null,
		credit_line: 'Gift of Mehak Vieira',
		catalogue_display: null,
		publication_history:
			'Sarah M. Estrela, "Conduits", in Antawan I. Byrd and Elvira Dyangani Ose, Project a Black Planet, exh. cat. (New Haven and London: Yale University Press, 2024), 344-7, fig. 358.',
		exhibition_history:
			'The Art Institute of Chicago, Project a Black Planet: The Art and Culture of Panafrica, Dec. 15, 2024-Mar. 30, 2025; MACBA Museu d’Art Contemporani de Barcelona, Nov. 5, 2025-Apr. 6, 2026; London, Barbican Centre for Arts and Conferences, Jun. 10-Sep. 6, 2026; KANAL-Centre Pompidou Bruxelles, Feb. 1-Apr. 30, 2027 (Chicago only).',
		provenance_text:
			'Commissioned by Mehak Vieira, Jahmek Contemporary Art, Angola, 2019 [email correspondence with Mehak Viera, founder and Managing Director, Jahmek Contemporary Art, Sept. 19, 2023; copy in curatorial object file]; given to the Art Institute of Chicago, 2024.',
		edition: null,
		publishing_verification_level: 'Web Everything',
		internal_department_id: 4,
		fiscal_year: 2024,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: true,
		max_zoom_window_size: 1280,
		copyright_notice: '© 2019 Yonamine and John Arthur Liebenberg.',
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 38,
			l: 38,
			s: 56,
			percentage: 0.00004525962305862383,
			population: 32,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Textile',
		artwork_type_id: 5,
		department_title: 'Textiles',
		department_id: 'PC-14',
		artist_id: 118413,
		artist_title: 'Yonamine',
		alt_artist_ids: [118415, 118414],
		artist_ids: [118415, 118414, 118413],
		artist_titles: [
			'Jahmek Contemporary Art',
			'John Arthur Liebenberg',
			'Yonamine',
		],
		category_ids: ['PC-14'],
		category_titles: ['Textiles'],
		term_titles: [
			'textile',
			'cotton (fiber)',
			'weaving',
			'21st Century',
			'warfare',
			'geometric',
			'printed textile',
			'weaving',
			'pigment',
			'printing',
			'african',
			'contemporary',
			'colonialism',
			'history',
			'people',
			'politics',
			'weapons',
			'African Textiles',
		],
		style_id: 'TM-12913',
		style_title: '21st Century',
		alt_style_ids: ['TM-5999', 'TM-12062'],
		style_ids: ['TM-12913', 'TM-5999', 'TM-12062'],
		style_titles: ['21st Century', 'african', 'contemporary'],
		classification_id: 'TM-69',
		classification_title: 'textile',
		alt_classification_ids: ['TM-2352', 'TM-159', 'TM-16069'],
		classification_ids: ['TM-69', 'TM-2352', 'TM-159', 'TM-16069'],
		classification_titles: [
			'textile',
			'printed textile',
			'weaving',
			'African Textiles',
		],
		subject_id: 'TM-13073',
		alt_subject_ids: [
			'TM-9124',
			'TM-14793',
			'TM-8818',
			'TM-8810',
			'TM-14438',
			'TM-12304',
		],
		subject_ids: [
			'TM-13073',
			'TM-9124',
			'TM-14793',
			'TM-8818',
			'TM-8810',
			'TM-14438',
			'TM-12304',
		],
		subject_titles: [
			'warfare',
			'geometric',
			'colonialism',
			'history',
			'people',
			'politics',
			'weapons',
		],
		material_id: 'TM-3081',
		alt_material_ids: ['TM-2509'],
		material_ids: ['TM-3081', 'TM-2509'],
		material_titles: ['cotton (fiber)', 'pigment'],
		technique_id: 'TM-4292',
		alt_technique_ids: ['TM-3861'],
		technique_ids: ['TM-4292', 'TM-3861'],
		technique_titles: ['weaving', 'printing'],
		theme_titles: [],
		image_id: '3a33435e-482d-73c1-334c-2e2e6fbac5ae',
		alt_image_ids: [
			'7c6f9742-db71-e649-e52c-81f75ff6abac',
			'e27c259a-2349-d60a-3c79-2c63b54a1fed',
			'7938e3dd-a8aa-725b-6230-4848dedf090c',
			'31bb75ce-ceb8-c8d8-3b4c-e8f6785ba888',
			'96669366-3146-a5f3-ace6-41ba2bafd671',
		],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2024.210'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Panoafricano'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:35:19-05:00',
		updated_at: '2025-04-10T16:40:27-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 248826,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/248826',
		is_boosted: false,
		title: '2016 in Museums, Money, and Politics',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAAMnHys/Jys3I0szN0MvL187N18/O2NLN0dLO0tHO19XT19TR2t7a2t/b29vb3N/c3+He3t3d4N7d4OHf4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURIDRFDpIIgLIUA2IQQRM9TQgAOw==',
			width: 6004,
			height: 7995,
			alt_text: 'A work made of color inkjet print on white wove paper.',
		},
		main_reference_number: '2019.1180',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 2018,
		date_end: 2018,
		date_display: '2018',
		date_qualifier_title: '',
		date_qualifier_id: null,
		artist_display: 'Andrea Fraser\nAmerican, born 1965',
		place_of_origin: null,
		description: null,
		short_description: null,
		dimensions: 'Paper: 174 × 151 cm (68 1/2 × 59 7/16 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 151,
				height: 174,
				diameter: null,
				clarification: 'Paper',
			},
		],
		medium_display: 'Color inkjet print on white wove paper',
		inscriptions: null,
		credit_line: 'Contemporary Art Purchase Fund',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: "1 of 12, plus 3 artist's proofs",
		publishing_verification_level: 'Web Basic',
		internal_department_id: 246,
		fiscal_year: 2020,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: false,
		max_zoom_window_size: 843,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 203,
			l: 40,
			s: 98,
			percentage: 0.0005437275712376865,
			population: 261,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Print',
		artwork_type_id: 18,
		department_title: 'Contemporary Art',
		department_id: 'PC-8',
		artist_id: 106766,
		artist_title: 'Andrea Fraser',
		alt_artist_ids: [],
		artist_ids: [106766],
		artist_titles: ['Andrea Fraser'],
		category_ids: ['PC-8'],
		category_titles: ['Contemporary Art'],
		term_titles: [
			'museums',
			'print',
			'politics',
			'Money',
			'institutional critique',
		],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: null,
		classification_title: null,
		alt_classification_ids: ['TM-17'],
		classification_ids: ['TM-17'],
		classification_titles: ['print'],
		subject_id: 'TM-12512',
		alt_subject_ids: ['TM-14438', 'TM-14437', 'TM-14436'],
		subject_ids: ['TM-12512', 'TM-14438', 'TM-14437', 'TM-14436'],
		subject_titles: ['museums', 'politics', 'Money', 'institutional critique'],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: [],
		image_id: '07b59e97-a0ad-4398-5a4c-4012a9c2225e',
		alt_image_ids: [],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2019.1180'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['2016 in Museums, Money, and Politics'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:32:54-05:00',
		updated_at: '2025-04-10T16:35:23-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 72921,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/72921',
		is_boosted: false,
		title: 'Black Tuesday',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhAwAFAPMAAElJSV5eXmtra3BwcJeXl6mpqa6ursnJyczMzNnZ2dvb297e3uPj4+Xl5enp6QAAACH5BAAAAAAAIf8LSW1hZ2VNYWdpY2sOZ2FtbWE9MC40NTQ1NDUALAAAAAADAAUAAAQLcBHVQnKCIXDKMBEAOw==',
			width: 1185,
			height: 2250,
			alt_text:
				'A work made of jute and wool, square knotted with cascading ends and wool pile.',
		},
		main_reference_number: '1988.483',
		has_not_been_viewed_much: false,
		boost_rank: null,
		date_start: 1968,
		date_end: 1968,
		date_display: '1968',
		date_qualifier_title: 'Made',
		date_qualifier_id: 4,
		artist_display:
			'Claire Zeisler (American, 1903–1991)\nChicago, United States',
		place_of_origin: 'Chicago',
		description: null,
		short_description: null,
		dimensions: '210 × 150 cm (84 × 60 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 150,
				height: 210,
				diameter: null,
				clarification: null,
			},
		],
		medium_display:
			'Jute and wool, square knotted with cascading ends and wool pile',
		inscriptions: null,
		credit_line: 'Gift of Borg-Warner Corporation',
		catalogue_display: null,
		publication_history:
			'Thomas Willis, “When String or Rope Becomes Art,” Chicago Tribune (Sept. 15, 1968) (ill.).\n\nWhitney Halsted, “Claire Zeisler and the Sculptured Knot, Craft Horizons 28, no. 5 (Sept.–Oct. 1968): 15 (ill.).\n\nSculpture. Sculpture? Sculpture!, exh. cat. (Highland Park, IL: Ravinia Festival, 1969), cat. 45 (not ill.).\n\nUniversity of Notre Dame Contemporary Arts Festival, Contemporary Arts in the Midwest (South Bend, IL: University of Notre Dame, 1970), cat. 44.\n\nArtweek, 2, 11 (Mar. 13, 1971): 1 (ill.).\n\nBarbara Kastern, “Fiber Sculpture,” Art Week , 2, 12 (Mar. 20, 1971): 8.\n\nPhiladelphia Museum of Art, American Crafts (Philadelphia: Philadelphia Museum of Art, 1977), 38, 44 (ill.).\n\nMuseum of Art, Washington State University, Diverse Directions: The Fiber Arts (Pullman, WA: Washington State University, 1978), cat. 39.\n\nChrista C. Mayer Thurman, ed., Claire Zeisler–A Retrospective, exh. cat. (Chicago: Art Institute of Chicago, 1979), 36–37, cat. 10 (ill.).',
		exhibition_history:
			'Chicago, Richard Feigen Gallery, Claire Zeisler’s Forms from Fiber, Sept. 18–Oct. 19, 1968; traveled to Richard Feigen Gallery, NY, Mar. 2–21, 1969.\n\nHighland Park, IL, Ravinia Festival, Sculpture. Sculpture? Sculpture! Summer, 1969.\n\nSouth Bend, IN, University of Notre Dame Contemporary Arts Festival, Contemporary Art in the Midwest, 1970.\n\nOakland, CA, California College of Arts and Crafts Gallery, Dimension in Fiber, Mar. 4–9, 1971.\n\nNew York, Hadler Galleries, Claire Zeisler, Nov. 20, 1976–Jan. 8, 1977.\n\nPhiladelphia Museum of Art, American Crafts 1977, Oct. 3–30, 1977.\n\nPhiladelphia, PA, Memorial Hall, The Philadelphia Craft Show, Nov. 3–6, 1977.\n\nPullman, WA, Museum of Art, Washington State University, Diverse Directions: The Fiber Arts, Oct.13–Nov. 17, 1978.\n\nArt Institute of Chicago, Claire Zeisler–A Retrospective, Feb. 10–May 20, 1979, cat. 10.',
		provenance_text:
			'With Richard Feigen Gallery, Chicago [Claire Zeisler’s Forms from Fiber 1968]. Hadler/Rodriguez Galleries, New York, and Houston, TX, by 1979 [Thurman 1979, cat. 10]. Borg-Warner Corporation, Chicago, by 1988 [incoming receipt RX17362, Aug. 12, 1988; copy in curatorial object file]; given to the Art Institute of Chicago, 1988.',
		edition: null,
		publishing_verification_level: 'Web Cataloged',
		internal_department_id: 4,
		fiscal_year: 1989,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: true,
		max_zoom_window_size: -1,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 0,
			l: 52,
			s: 0,
			percentage: 0.014596452543376284,
			population: 197,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Textile',
		artwork_type_id: 5,
		department_title: 'Textiles',
		department_id: 'PC-14',
		artist_id: 37413,
		artist_title: 'Claire Zeisler',
		alt_artist_ids: [],
		artist_ids: [37413],
		artist_titles: ['Claire Zeisler'],
		category_ids: ['PC-14', 'PC-825', 'PC-154'],
		category_titles: ['Textiles', 'Women artists', 'Chicago Artists'],
		term_titles: [
			'knotting',
			'jute',
			'Chicago',
			'textile',
			'needlework (visual works)',
			'fiber art',
			'wool (textile)',
		],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: 'TM-69',
		classification_title: 'textile',
		alt_classification_ids: ['TM-83', 'TM-10653'],
		classification_ids: ['TM-69', 'TM-83', 'TM-10653'],
		classification_titles: [
			'textile',
			'needlework (visual works)',
			'fiber art',
		],
		subject_id: 'TM-12075',
		alt_subject_ids: [],
		subject_ids: ['TM-12075'],
		subject_titles: ['Chicago'],
		material_id: 'TM-3084',
		alt_material_ids: ['TM-2581'],
		material_ids: ['TM-3084', 'TM-2581'],
		material_titles: ['jute', 'wool (textile)'],
		technique_id: 'TM-4210',
		alt_technique_ids: [],
		technique_ids: ['TM-4210'],
		technique_titles: ['knotting'],
		theme_titles: ['Women artists', 'Chicago Artists'],
		image_id: '051ae153-4216-c45c-e7db-65a05fb02e63',
		alt_image_ids: ['3e039cb1-b8f1-f50b-d155-c378f423cd6a'],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['1988.483'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Black Tuesday'],
				weight: 497,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:27:17-05:00',
		updated_at: '2025-04-10T16:30:22-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 56108,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/56108',
		is_boosted: false,
		title: 'Red Preview',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBAAFAPMAAAAAAAkBAAsBABMCAhUCAh0DBxwDCD4JCVILC1cLC1ILElIME3IQEHgREAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAQOEAwCwDk1ISAaC4WyGBEAOw==',
			width: 1787,
			height: 2250,
			alt_text:
				'A work made of jute, flanges square knotted and wrapped; cascading ends.',
		},
		main_reference_number: '1979.294',
		has_not_been_viewed_much: false,
		boost_rank: null,
		date_start: 1969,
		date_end: 1969,
		date_display: '1969',
		date_qualifier_title: 'Made',
		date_qualifier_id: 4,
		artist_display:
			'Claire Zeisler (American, 1903–1991)\nChicago, United States',
		place_of_origin: 'Chicago',
		description: null,
		short_description: null,
		dimensions: '240 × 150 cm (96 × 60 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 150,
				height: 240,
				diameter: null,
				clarification: null,
			},
		],
		medium_display: 'Jute, flanges square knotted and wrapped; cascading ends',
		inscriptions: null,
		credit_line: 'Gift of Claire Zeisler',
		catalogue_display: null,
		publication_history:
			'Sculpture. Sculpture? Sculpture!, exh. cat. (Highland Park, IL: Ravinia Festival, 1969), cat. 46 (not ill.).\n\nDona Z. Meilach, Macramé, Creative Design in Knotting (New York: Crown Publishers, 1971), 128 (ill.).\n\nMuseum of Contemporary Crafts of the American Craftsmen\'s Council, Sculpture in Fiber, exh. cat. (New York: American Craft Council, 1972), (ill.).\n\nMildred Constantine and Jack Lenor Larsen, Beyond Craft: The Art of Fabric (New York: Van Nostrand Reinhold, 1972), 290.\n\nImelda DeGraw, Fibre Structures: An Exhibition of Contemporary Textiles, exh. cat. (Denver: Denver Art Museum, 1972) cat.  51.\n\nChicago Public Library, Masterpieces of Recent Chicago Art, exh. cat. (Chicago: Chicago Public Library, 1977), cat. 64.\n\nDiane Kirkpatric, Charles Lewis, and Cynthia Yao, eds., Chicago: The City and Its Artists, 1945-1978, exh. cat. (Ann Arbor: University of Michigan Museum of Art, 1978), cat. 35.\n\nBernard Kester, Ritual Forms of Claire Zeisler in Craft Horizons (April 1979): 58-59 (Ill.)\n\nChrista C. Mayer Thurman, ed., Claire Zeisler-A Retrospective, exh. cat. (Chicago: The Art Institute of Chicago, 1979), 46-47.\n\nChristopher Lyon, A Woman of Fiber, Chicago Magazine (Nov. 1985): 161 (ill.).\n\nCynthia Fowler, "A Sign of the Times: Sheila Hicks, the Fiber Arts Movement, and the Language of Liberation," The Journal of Modern Craft 2, 1 (Mar. 2014): 8, 33-52, fig, 2.',
		exhibition_history:
			"Highland Park, IL, Ravinia Festival, Sculpture. Sculpture? Sculpture!, Summer 1969, cat.\n\nNew York, Museum of Contemporary Crafts of The American Craftsmen's Council, Sculpture in Fiber, Jan. 27–Apr. 2, 1972, cat.\n\nDenver Art Museum, Fibre Structures: An Exhibition of Contemporary Textiles, May 9–June 18, 1972, cat..\n\nChicago Public Library Cultural Center, Masterpieces of Recent Chicago Art, Oct. 3–Nov. 2, 1977, cat.\n\nAnn Arbor, MI, University of Michigan Museum of Art, Chicago: The City and Its Artists, 1945–1978, Mar. 17–Apr. 28, 1978, cat.\n\nArt Institute of Chicago, Claire Zeisler-A Retrospective, Feb. 10–May 20, 1979, cat.\n\nNew York, Whitney Museum of American Art, Claire Zeisler: Works from 1962–1984, Dec. 12, 1984–Mar. 12, 1985.\n\nChicago, Museum of Contemporary Art, Art in Chicago, 1945–1995, Nov. 16, 1996–Mar. 23, 1997.",
		provenance_text:
			'The artist, Chicago [Incoming receipt RX11920, Jan. 26, 1979; letter from the artist, June 15, 1979; copies in curatorial object file]; given to the Art Institute of Chicago, May 1979.',
		edition: null,
		publishing_verification_level: 'Web Cataloged',
		internal_department_id: 4,
		fiscal_year: null,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: true,
		max_zoom_window_size: -1,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 61.4596,
		color: {
			h: 359,
			l: 32,
			s: 84,
			percentage: 0.08798968720616532,
			population: 787,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Textile',
		artwork_type_id: 5,
		department_title: 'Textiles',
		department_id: 'PC-14',
		artist_id: 37413,
		artist_title: 'Claire Zeisler',
		alt_artist_ids: [],
		artist_ids: [37413],
		artist_titles: ['Claire Zeisler'],
		category_ids: ['PC-14', 'PC-825', 'PC-154'],
		category_titles: ['Textiles', 'Women artists', 'Chicago Artists'],
		term_titles: [
			'Chicago',
			'textile',
			'weaving',
			'fiber',
			'fiber art',
			'fiber construction',
		],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: 'TM-69',
		classification_title: 'textile',
		alt_classification_ids: ['TM-159', 'TM-356', 'TM-10653', 'TM-10391'],
		classification_ids: ['TM-69', 'TM-159', 'TM-356', 'TM-10653', 'TM-10391'],
		classification_titles: [
			'textile',
			'weaving',
			'fiber',
			'fiber art',
			'fiber construction',
		],
		subject_id: 'TM-12075',
		alt_subject_ids: [],
		subject_ids: ['TM-12075'],
		subject_titles: ['Chicago'],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: ['Women artists', 'Chicago Artists'],
		image_id: '136d3f56-82b4-12e8-dc65-65059f7c8b8e',
		alt_image_ids: ['331e7e1d-f4c8-3ec0-6519-cf78ee212762'],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['1979.294'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Red Preview'],
				weight: 1045,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:27:17-05:00',
		updated_at: '2025-04-10T16:30:22-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 259352,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/259352',
		is_boosted: false,
		title: 'Mise-en-scène: Commemorative Toile',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBwAFAPUAAE9BN1xDM2NQQmdTSGVaUHFkV4NoW4VsXY5wVYxzX5p1XIJvYoJzbJ93YJR7YIN7dad/aZeAZJ6AYp+KdqOEY6SHZquCaquCa66EbKWKaaqQb66Ld7aSfKiUg7uVgL+bhb6bh8Shi8GhkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAHAAUAAAYhwI0I5AmBOA2LBXMwQBILAWAQUEQKhAcDQdFkHJ2JpBIEADs=',
			width: 7923,
			height: 5792,
			alt_text: 'A work made of mixed media.',
		},
		main_reference_number: '2020.346a-c',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 1992,
		date_end: 1993,
		date_display: '1992-93',
		date_qualifier_title: '',
		date_qualifier_id: null,
		artist_display: 'Renée Green \nAmerican, born 1959',
		place_of_origin: 'United States',
		description:
			'<p>Renée Green’s <em>Mise-en-scène: Commemorative Toile</em> is a constructed interior scene that evokes the material and social histories of the trans-Atlantic slave trade, while serving as a pivotal example of the artist’s conceptual and iterative approach to installation. Green sets the stage of her anachronistic period room with pastel-pink floral wallpaper, drapery, and an upholstered stool; sculptural props and archival curiosities; and a music box labeled “Ambience” emitting an 18th-century baroque French melody. The connective tissue of Green’s décor is a French textile known as <em>toile</em>, a decorative fabric featuring idyllic pastoral vignettes originally imported from Southeast Asia in the 17th century. While in residency in Clisson, France in 1991, Green began researching the relationship between the production of <em>toile</em> in France and the region’s participation in the triangular colonial trade routes between Europe, Africa, and the Americas. In <em>Mise-en-scène: Commemorative Toile</em>, Green demystifies the social relations surrounding the fabric’s production, subtly imbuing it with the stuff of its own making—horrific scenes of enslavement and uprisings in French colonies. Transitioning from the wall to the floor and from the ornamental to the archival, Green positions three card file boxes, scaled to the body, on the ground in a triangle formation. Slotted within are cards chronicling the names of French slave ships, the languages Africans spoke upon boarding, and the active years of the enterprise; their dense organization emulates the way in which African bodies were serially filed into vessels crossing the Atlantic. Motorized toy boats circle endlessly in empty basins connecting the three points, suggesting that the triangle trade continues to spin the wheels of global capitalism and that the colonial past is a constant specter of the present.</p><p>Since the early 1990s Renée Green’s multidisciplinary practice has manifested in complex, research-driven installations—combining text, image, object, and time-based media—that build upon strategies and histories of Conceptual art and institutional critique from the 1960s and 1970s. <em>Mise-en-scene: Commemorative Toile</em> is a key example, as Green takes up what Belgian conceptualist Marcel Broodthaers (1924–1976) termed <em>esprit décor</em>, staging the interior scene as a site for questioning the ways in which history is constructed, displayed, and inhabited in domestic and institutional settings. At once site-specific and diffuse, the work accumulates new meaning as it populates shifting exhibition contexts; the artist’s installations using <em>toile</em> have toured Europe and the United States in various configurations, occupying the wall, furniture, and even bodies. Referred to by writer Joe Wood as a “one-woman diaspora,” Green’s expansive artworks map global cultural flows across multiple timelines, from the trans-Atlantic slave trade to the international appropriation of hip-hop. As the title and strategies of <em>Mise-en-scène</em> suggest, the artist’s critical stagecraft implicates viewers into unfolding dramas in which fact and fiction, public recollection and private memory collide.</p>\n',
		short_description: null,
		dimensions: 'Dimensions variable',
		dimensions_detail: [],
		medium_display: 'Mixed Media',
		inscriptions: null,
		credit_line: 'Claire and Gordon Prussian Fund for Contemporary Art',
		catalogue_display: null,
		publication_history:
			'Russell Ferguson, Renée Green: World Tour, exh. cat. (Los Angeles: Museum of Contemporary Art, 1993), D23-D32 (color ills.).\n\nSusan Kandal, "World Tour: A Look at Race, Politics and Power," Los Angeles Times, Apr. 8, 1993, F10-11.\n\nHuey Copeland, “Renée Green’s Diasporic Imagination," in Bound to Appear: Art, Slavery, and the Site of Blackness in Multicultural America (Chicago: Chicago University Press, 2013), 159 (color ill.), 160, 174-177, 178 (ill., details), 179, 180 (color ill., detail), 181-183, 184-185 (color ill., details), 186-189.',
		exhibition_history:
			'Los Angeles, Museum of Contemporary Art, Renée Green: World Tour, Mar. 28–May 16, 1993, no cat. no.; Dallas Museum of Art, Nov. 20, 1993–Jan. 16, 1994.',
		provenance_text:
			'The artist and Free Agent Media; sold through Bortolami Gallery, New York, to the Art Institute of Chicago, Nov. 10, 2020.',
		edition: null,
		publishing_verification_level: 'Web Cataloged',
		internal_department_id: 246,
		fiscal_year: 2021,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: true,
		max_zoom_window_size: 1280,
		copyright_notice: '© 1992-1993 Renée Green and Free Agent Media',
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 3,
			l: 31,
			s: 43,
			percentage: 0.00027239040404779984,
			population: 125,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: true,
		on_loan_display: null,
		gallery_title: 'Gallery 295',
		gallery_id: 25471,
		nomisma_id: null,
		artwork_type_title: 'Installation',
		artwork_type_id: 16,
		department_title: 'Contemporary Art',
		department_id: 'PC-8',
		artist_id: 55773,
		artist_title: 'Renée Green',
		alt_artist_ids: [],
		artist_ids: [55773],
		artist_titles: ['Renée Green'],
		category_ids: ['PC-8', 'PC-835'],
		category_titles: [
			'Contemporary Art',
			'2020–21 acquisitions by BIPOC artists',
		],
		term_titles: ['installation'],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: 'TM-1152',
		classification_title: 'installation',
		alt_classification_ids: [],
		classification_ids: ['TM-1152'],
		classification_titles: ['installation'],
		subject_id: null,
		alt_subject_ids: [],
		subject_ids: [],
		subject_titles: [],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: ['2020–21 acquisitions by BIPOC artists'],
		image_id: 'e53d6a66-6935-c043-94b8-af772c7e6202',
		alt_image_ids: [
			'efc89d0e-5954-fd3e-a295-5514ca9be186',
			'ffdb241c-7077-672a-6d36-3693ba50b4cd',
			'a70f8437-05d5-4bb6-2c14-abee613a4063',
			'ca4398ba-03c5-9afc-0962-6b17e9cfbcac',
			'459ae2ff-466b-7451-1872-e64c0ec64826',
		],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2020.346a-c'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Mise-en-scène: Commemorative Toile'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-04-10T16:20:22-05:00',
		updated_at: '2025-04-10T16:25:27-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 265993,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/265993',
		is_boosted: false,
		title: 'Untitled',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBwAFAPUAACQlNTo3P2Q9FlQ3MmhFLTk8YjQ9e0A+Qkc/R1tYWlxeY1VRenhvZYoyHaQzFplZEJVhPIt6M4R4cId8cLaTF8KXCMacCcmINMSSSzxBiEJFhUZLilRRhVJfon+GppeSlJCUscqcgMionAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAHAAUAAAYhQI4hoEAAChtP4kAQRDSgSSN0sWQ6EocIU1l8GAPIgxIEADs=',
			width: 9465,
			height: 7164,
			alt_text: 'A work made of oil on canvas.',
		},
		main_reference_number: '2022.577',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 1974,
		date_end: 1974,
		date_display: '1974',
		date_qualifier_title: '',
		date_qualifier_id: null,
		artist_display: 'Serge Chermayeff\nBritish, born Russia, 1900-1996',
		place_of_origin: 'England',
		description: null,
		short_description: null,
		dimensions: '132.1 × 106.7 cm (52 × 42 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 106,
				height: 132,
				diameter: null,
				clarification: null,
			},
		],
		medium_display: 'Oil on canvas',
		inscriptions: null,
		credit_line: 'Gift of Bauhaus Chicago Foundation',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: null,
		publishing_verification_level: 'Web Basic',
		internal_department_id: 25,
		fiscal_year: 2023,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: false,
		max_zoom_window_size: 843,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 51,
			l: 42,
			s: 87,
			percentage: 0.0010692070436115544,
			population: 725,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Painting',
		artwork_type_id: 1,
		department_title: 'Architecture and Design',
		department_id: 'PC-5',
		artist_id: 52349,
		artist_title: 'Serge Chermayeff',
		alt_artist_ids: [],
		artist_ids: [52349],
		artist_titles: ['Serge Chermayeff'],
		category_ids: ['PC-5'],
		category_titles: ['Architecture and Design'],
		term_titles: ['institute of Design'],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: null,
		classification_title: null,
		alt_classification_ids: [],
		classification_ids: [],
		classification_titles: [],
		subject_id: 'TM-13268',
		alt_subject_ids: [],
		subject_ids: ['TM-13268'],
		subject_titles: ['institute of Design'],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: [],
		image_id: '789377cc-ca49-8a17-8a98-bf41928070b7',
		alt_image_ids: [],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2022.577'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Untitled'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-01-28T09:58:40-06:00',
		updated_at: '2025-04-10T16:20:20-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 265992,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/265992',
		is_boosted: false,
		title: 'Untitled',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAAHZfT2hfUXBmVnJoV3FqWm5sZ355aH55bHZ6eolwXoZ6ZoZ/ao6OfGqFi32Hg5CVhpWWh4SWlZObk5espwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURoBQ5CTQ1gPIYAsEsQYEcQwgAOw==',
			width: 7510,
			height: 9592,
			alt_text: 'A work made of oil on canvas.',
		},
		main_reference_number: '2022.578',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 1979,
		date_end: 1979,
		date_display: '1979',
		date_qualifier_title: '',
		date_qualifier_id: null,
		artist_display: 'Serge Chermayeff\nBritish, born Russia, 1900-1996',
		place_of_origin: 'England',
		description: null,
		short_description: null,
		dimensions: '95.3 × 125.8 cm (37 1/2 × 49 1/2 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 125,
				height: 95,
				diameter: null,
				clarification: null,
			},
		],
		medium_display: 'Oil on canvas',
		inscriptions: null,
		credit_line: 'Gift of Bauhaus Chicago Foundation',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: null,
		publishing_verification_level: 'Web Basic',
		internal_department_id: 25,
		fiscal_year: 2023,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: false,
		max_zoom_window_size: 843,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: {
			h: 190,
			l: 54,
			s: 20,
			percentage: 0.0016783293667936776,
			population: 1209,
		},
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: false,
		on_loan_display: null,
		gallery_title: null,
		gallery_id: null,
		nomisma_id: null,
		artwork_type_title: 'Painting',
		artwork_type_id: 1,
		department_title: 'Architecture and Design',
		department_id: 'PC-5',
		artist_id: 52349,
		artist_title: 'Serge Chermayeff',
		alt_artist_ids: [],
		artist_ids: [52349],
		artist_titles: ['Serge Chermayeff'],
		category_ids: ['PC-5'],
		category_titles: ['Architecture and Design'],
		term_titles: ['institute of Design'],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: null,
		classification_title: null,
		alt_classification_ids: [],
		classification_ids: [],
		classification_titles: [],
		subject_id: 'TM-13268',
		alt_subject_ids: [],
		subject_ids: ['TM-13268'],
		subject_titles: ['institute of Design'],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: [],
		image_id: '11ec21b6-836c-89b3-270b-dfdb63385037',
		alt_image_ids: [],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2022.578'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['Untitled'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-01-28T09:58:40-06:00',
		updated_at: '2025-04-10T16:20:20-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
	{
		id: 264264,
		api_model: 'artworks',
		api_link: 'https://api.artic.edu/api/v1/artworks/264264',
		is_boosted: false,
		title: 'P.5. Growing Object',
		alt_titles: null,
		thumbnail: {
			lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAANDKxdPMx9nSzNnSzdnTzd3W0N3X0N7Y0d/Z0+DZ0uDZ0+Ha0+Lb0+Hb1eLb1eLc1ePc1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUPoCIqh2CIAWA4ggA5xxsCADs=',
			width: 7376,
			height: 9524,
			alt_text: 'A work made of offset lithograph on paper.',
		},
		main_reference_number: '2022.498',
		has_not_been_viewed_much: true,
		boost_rank: null,
		date_start: 1950,
		date_end: 1950,
		date_display: '1950',
		date_qualifier_title: '',
		date_qualifier_id: null,
		artist_display: 'Serge Chermayeff\nBritish, born Russia, 1900-1996',
		place_of_origin: 'England',
		description: null,
		short_description: null,
		dimensions: '56.5 × 43.5 cm (22 1/16 × 17 in.)',
		dimensions_detail: [
			{
				depth: null,
				width: 43,
				height: 56,
				diameter: null,
				clarification: null,
			},
		],
		medium_display: 'Offset lithograph on paper',
		inscriptions: null,
		credit_line:
			'Purchased with funds provided by the Igel and Dunn families in honor of Daisy Igel; Margaret Fisher Endowment Fund; Photography and Media Committee Purchase Fund',
		catalogue_display: null,
		publication_history: null,
		exhibition_history: null,
		provenance_text: null,
		edition: null,
		publishing_verification_level: 'Web Basic',
		internal_department_id: 25,
		fiscal_year: 2023,
		fiscal_year_deaccession: null,
		is_public_domain: false,
		is_zoomable: false,
		max_zoom_window_size: 843,
		copyright_notice: null,
		has_multimedia_resources: false,
		has_educational_resources: false,
		has_advanced_imaging: false,
		colorfulness: 0,
		color: null,
		latitude: null,
		longitude: null,
		latlon: null,
		is_on_view: true,
		on_loan_display: null,
		gallery_title: 'Gallery 285',
		gallery_id: 23970,
		nomisma_id: null,
		artwork_type_title: 'Print',
		artwork_type_id: 18,
		department_title: 'Architecture and Design',
		department_id: 'PC-5',
		artist_id: 52349,
		artist_title: 'Serge Chermayeff',
		alt_artist_ids: [],
		artist_ids: [52349],
		artist_titles: ['Serge Chermayeff'],
		category_ids: ['PC-5'],
		category_titles: ['Architecture and Design'],
		term_titles: ['institute of Design'],
		style_id: null,
		style_title: null,
		alt_style_ids: [],
		style_ids: [],
		style_titles: [],
		classification_id: null,
		classification_title: null,
		alt_classification_ids: [],
		classification_ids: [],
		classification_titles: [],
		subject_id: 'TM-13268',
		alt_subject_ids: [],
		subject_ids: ['TM-13268'],
		subject_titles: ['institute of Design'],
		material_id: null,
		alt_material_ids: [],
		material_ids: [],
		material_titles: [],
		technique_id: null,
		alt_technique_ids: [],
		technique_ids: [],
		technique_titles: [],
		theme_titles: [],
		image_id: '7a848834-3247-b76d-0cf7-750ed48b6f49',
		alt_image_ids: [],
		document_ids: [],
		sound_ids: [],
		video_ids: [],
		text_ids: [],
		section_ids: [],
		section_titles: [],
		site_ids: [],
		suggest_autocomplete_all: [
			{
				input: ['2022.498'],
				contexts: {
					groupings: ['accession'],
				},
			},
			{
				input: ['P.5. Growing Object'],
				weight: 1,
				contexts: {
					groupings: ['title'],
				},
			},
		],
		source_updated_at: '2025-02-27T10:20:56-06:00',
		updated_at: '2025-04-10T16:20:20-05:00',
		timestamp: '2025-04-10T19:12:06-05:00',
	},
];
